[project]
name = "yt_minecraft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    #--------------------------------------------------------------------
    # DATA MANIPULTION - Processamento de dados
    #--------------------------------------------------------------------
    "polars>=0.20.0", 
    "pyarrow>=14.0.0",

    #--------------------------------------------------------
    # HTTP & API requests - Para comunicação com Spotify API
    #--------------------------------------------------------
    "requests>=2.31.0,<3.0.0",

    #--------------------------------------------------------------------
    # ENVIRONMENT & CONFIGURATION - To manage environment variables
    #--------------------------------------------------------------------
    "python-dotenv>=1.0.0,<2.0.0",

    #--------------------------------------------------------------------
    #DATE & TIME HANDLING - Dates and timezones manipulation
    #--------------------------------------------------------------------
    "python-dateutil>=2.8.2,<3.0.0",
    "pytz==2024.1",
    "pendulum==3.0.0",


    #--------------------------------------------------------------------
    #DATABASE DRIVERS - Drivers para conexão com PostgreSQL
    #--------------------------------------------------------------------
    "psycopg2-binary>=2.9.0,<3.0.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/yt_minecraft"]

[project.optional-dependencies]
airflow = [
    #--------------------------------------------------------
    # AIRFLOW PROVIDERS - Extensões necessárias para Airflow
    #--------------------------------------------------------
    "apache-airflow-providers-postgres",
    "apache-airflow-providers-celery",
    "apache-airflow-providers-docker>=3.0.0,<4.0.0",
]

[dependency-groups]
dev = [
    "ipython>=8.18.0",
    "jupyter>=1.0.0",
    "ipykernel>=7.2.0",
]
